### ISSUE TITLE
Wrong IP address used.

### ISSUE THREAD

**Issue by Kravimir** [Epchk/Tablo_Lite#1]
Where does the IP address entered in the form actually get used (besides being written to and read from the cookie)? The hard-coded IP address seems to be an entirely separate variable.

P.S. You can simplify some of your code by using the [location.hash property](https://developer.mozilla.org/en-US/docs/Web/API/Location/hash).

**Comment by Epchk** [comment]
I hardcoded the IP address in tablo_ota.js right at the start with my actual IP address and then never got around to making the callback to actually change it when I added the settings page. Oops.

**Comment by Epchk** [comment]
Updating the IP Address in the Setup section should now properly change the IP address used to connect to the tablo. You should no longer need to change the default value in tablo_ota.js. I've also updated a new Beta release with this change.
